### ISSUE TITLE
How does MMS capture Dependencies and non-mxnet-Models into a Model Archive?

### ISSUE THREAD

**Issue by henningsway** [awslabs/mxnet-model-server#817]
I am currently researching a good way to package my trained models with their specific dependencies into a model-archive.

I've checked out the [docs](https://github.com/awslabs/mxnet-model-server/blob/master/model-archiver/README.md), but it is not yet clear to me, how the (python) dependencies of my model are captured with the model and restored at runtime.

Also, I would like to better understand, how non-mxnet-Models (say tensorflow) can be packaged into an `*.mar`. I suppose it works as custom training service maybe? If I had custom preprocessing artifacts (say a scaler), how would these be included in the model?

One reasons I am interested in in this is due to the perception that MMS not seem to fully fit my specific serving requirements (due to synchronous REST API). But I still need to solve the "model archive" problem and would be interested to reuse your tools and conventions in a custom (docker-based) serving solution.

**Comment by vdantu** [comment]
@henningsway : Model archive is simply an archive of arbitrary files. As a part of this model-archive you would need to provide a custom service python file. This file understands how to load the model, run preprocess, run inference and run post process. This is a mandatory file that you would need to provide. Now, you could package other python modules within this model-archive. All you would need to do is add all the dependent python modules into the same folder from which you would create the model-archive. 
Model server will unarchive it, put it in its temp cache and add this cached location to the PYTHONPATH. Since all your archived python modules are in the PYTHONPATH, you would be able to just run "import my_module" and it would run. 

Is this helpful?  

Regarding synchronous REST API, we have offline services using the model server. Could you please elaborate a little more on the use case. You could also join our slack channel for more real-time conversations :)

**Comment by henningsway** [comment]
Perfect, thank you so much for these suggestions. :)

**Comment by vdantu** [comment]
Some of the things you might want to consider are
1. How many hops do you have between the actual ingress of requests to the actual compute? I can see three hops atleast. The actual request handling (which can be a storage location or be a HTTP request handler), Queuing (RabbitMQ in your case) and compute(actual model code). This means multiple IPC calls and thus increase in latencies. If this is completely offline, then you might not worry about it :)
2. MMS also provides request batching, which we have seen to increase the throughput performance by 2-3 times on GPU hosts. 
3. Managing the compute worker's lifecycle, ie., restarting if something goes wrong with the inference and trying keep all the workers up might be a complex problem to solve. Using simple Nanny processes to keep workers up and running can get complex. 

I would still think MMS could provide value, but you might have to evaluate if the benefits out weight the costs :) . Do let us know your thoughts.

**Comment by henningsway** [comment]
I have actually chosen the "custom" docker route for now. Thank you very much for sharing your insights here. The MMS-feature set will continue to grow, so I might reconsider in the future.

All the best! :)
